export const jobData = [
  {
    jobTitle: "Web Developer",
    jobDescription:
      "As a Web Developer, you'll be responsible for designing, coding, and modifying websites, from layout to function, according to client specifications. You will collaborate closely with designers and other developers to create visually appealing sites that feature user-friendly design and clear navigation. Stay updated on emerging technologies.",
    responsibilities: [
      "Develop responsive and dynamic websites.",
      "Collaborate with designers to match visual design intent.",
      "Maintain, expand, and scale websites.",
      "Stay updated on the latest web trends.",
      "Ensure site security and data protection.",
      "Optimize site performance and speed.",
    ],
    qualifications: [
      "Proficiency in HTML, CSS, JavaScript, and frameworks like React or Angular.",
      "Experience with server-side technologies (Node.js, PHP).",
      "Strong problem-solving skills.",
      "Familiarity with responsive design principles.",
      "Ability to work independently and as part of a team.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 3,
    education: "Bachelor's or Master's degree in Computer Science or a related field from a recognized university is preferred.However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 1 + years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "31 September, 2024",
    salary: "TK 25-60K (Based on experience)",
    location: "Chittagong, Bangladesh",
  },
  {
    jobTitle: "Digital Marketing Specialist",
    jobDescription:
      "The Digital Marketing Specialist will focus on managing online marketing strategies, analyzing data to optimize campaigns, and increasing brand awareness. You will be tasked with planning and executing digital marketing campaigns, including web, SEO/SEM, email, social media, and display advertising. You will also analyze and report on campaign performance.",
    responsibilities: [
      "Develop and execute digital marketing strategies.",
      "Manage SEO and SEM strategies.",
      "Analyze and optimize advertising campaigns.",
      "Create content for social media platforms.",
      "Collaborate with the sales team for better results.",
      "Track and report website traffic and social media performance.",
    ],
    qualifications: [
      "Experience with SEO, Google Analytics, and SEM.",
      "Proficient in social media marketing.",
      "Strong analytical and project management skills.",
      "Excellent communication and teamwork skills.",
      "Bachelor’s degree in Marketing or related field.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 2,
    salary: "TK 20-45k (Based on experience)",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 2 years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "31 September, 2024",
    location: "Chittagong, Bangladesh",
  },
  {
    jobTitle: "Junior Content Writer",
    jobDescription:
      "As a Junior Content Writer, you will assist in creating engaging content for our websites, blogs, and social media platforms. Your main goal will be to write, edit, and proofread content to ensure quality and clarity. You will work closely with the marketing team to align content with our brand's voice and objectives.",
    responsibilities: [
      "Write and edit blog posts, articles, and web content.",
      "Research industry-related topics for content creation.",
      "Collaborate with designers for content layout.",
      "Update and manage content on social media platforms.",
      "Ensure all-around consistency of tone and style.",
    ],
    qualifications: [
      "Excellent writing and editing skills.",
      "Familiarity with SEO principles.",
      "Knowledge of online content strategy.",
      "Attention to detail and time-management skills.",
      "Bachelor’s degree in English, Journalism, or related field.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    education: "Bachelor's or Master's degree in Computer Science or a related field from a recognized university is preferred.However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    vacancy: 1,
    education: "Bachelor's or Master's degree in any Subject from a recognized university is preferred.However, we are open to considering candidates with exceptional experience in lieu of formal qualifications. Must have very good writing skills.",
    jobType: "On-site",
    jobCategory: "Full-time",
    experience: " Fresher",
    salary: "TK 15-20k (Based on experience)",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "31 September, 2024",
    location: "Chittagong, Bangladesh",
  },
];
