export const jobData = [
  {
    jobTitle: "Web Developer",
    jobDescription:
      "As a Web Developer, you'll be responsible for designing, coding, and modifying websites, from layout to function, according to client specifications. You will collaborate closely with designers and other developers to create visually appealing sites that feature user-friendly design and clear navigation. Stay updated on emerging technologies.",
    responsibilities: [
      "Develop responsive and dynamic websites.",
      "Collaborate with designers to match visual design intent.",
      "Maintain, expand, and scale websites.",
      "Stay updated on the latest web trends.",
      "Ensure site security and data protection.",
      "Optimize site performance and speed.",
    ],
    qualifications: [
      "Proficiency in HTML, CSS, JavaScript, and frameworks like React or Angular.",
      "Experience with server-side technologies (Node.js, PHP).",
      "Strong problem-solving skills.",
      "Familiarity with responsive design principles.",
      "Ability to work independently and as part of a team.",
    ],
    officeTime: "9:00 AM - 6:00 PM",
    vacancy: 3,
    jobType: "On-site",
    workDays: "Sat - Thu (Alt. Saturday Off)",
    salary: "25-60",
    location: "Dhaka, Bangladesh",
  },
  {
    jobTitle: "Digital Marketing Specialist",
    jobDescription:
      "The Digital Marketing Specialist will focus on managing online marketing strategies, analyzing data to optimize campaigns, and increasing brand awareness. You will be tasked with planning and executing digital marketing campaigns, including web, SEO/SEM, email, social media, and display advertising. You will also analyze and report on campaign performance.",
    responsibilities: [
      "Develop and execute digital marketing strategies.",
      "Manage SEO and SEM strategies.",
      "Analyze and optimize advertising campaigns.",
      "Create content for social media platforms.",
      "Collaborate with the sales team for better results.",
      "Track and report website traffic and social media performance.",
    ],
    qualifications: [
      "Experience with SEO, Google Analytics, and SEM.",
      "Proficient in social media marketing.",
      "Strong analytical and project management skills.",
      "Excellent communication and teamwork skills.",
      "Bachelor’s degree in Marketing or related field.",
    ],
    officeTime: "9:00 AM - 6:00 PM",
    vacancy: 2,
    salary: "20-45",
    jobType: "On-site",
    workDays: "Sat - Thu (Alt. Saturday Off)",
    location: "Dhaka, Bangladesh",
  },
  {
    jobTitle: "Junior Content Writer",
    jobDescription:
      "As a Junior Content Writer, you will assist in creating engaging content for our websites, blogs, and social media platforms. Your main goal will be to write, edit, and proofread content to ensure quality and clarity. You will work closely with the marketing team to align content with our brand's voice and objectives.",
    responsibilities: [
      "Write and edit blog posts, articles, and web content.",
      "Research industry-related topics for content creation.",
      "Collaborate with designers for content layout.",
      "Update and manage content on social media platforms.",
      "Ensure all-around consistency of tone and style.",
    ],
    qualifications: [
      "Excellent writing and editing skills.",
      "Familiarity with SEO principles.",
      "Knowledge of online content strategy.",
      "Attention to detail and time-management skills.",
      "Bachelor’s degree in English, Journalism, or related field.",
    ],
    officeTime: "9:00 AM - 6:00 PM",
    vacancy: 1,
    jobType: "On-site",
    salary: "10-20",
    workDays: "Sat - Thu (Alt. Saturday Off)",
    location: "Dhaka, Bangladesh",
  },
  {
    jobTitle: "Technical Support Engineer - (Laravel)",
    jobDescription:
      "The Technical Support Engineer (Laravel) will provide troubleshooting and technical support for applications built on Laravel. This role involves maintaining existing applications, resolving technical issues, and collaborating with the development team to improve the overall user experience. You will also handle bug fixes and assist in new feature rollouts.",
    responsibilities: [
      "Troubleshoot and resolve application issues.",
      "Collaborate with the development team for bug fixes.",
      "Assist in new feature implementation and testing.",
      "Ensure application security and performance.",
      "Respond to support tickets and resolve them efficiently.",
    ],
    qualifications: [
      "Experience with Laravel framework.",
      "Strong problem-solving and debugging skills.",
      "Knowledge of PHP, MySQL, and version control (Git).",
      "Ability to work under pressure and meet deadlines.",
      "Good communication skills and teamwork.",
    ],
    officeTime: "9:00 AM - 6:00 PM",
    vacancy: 2,
    jobType: "On-site",
    salary: "25-60",
    workDays: "Sat - Thu (Alt. Saturday Off)",
    location: "Dhaka, Bangladesh",
  },
  {
    jobTitle: "Technical Support Engineer - (Flutter)",
    jobDescription:
      "The Technical Support Engineer (Flutter) will handle issues related to mobile applications built on Flutter. You will work with the development team to resolve issues, provide solutions to customer queries, and assist in developing new features for mobile applications. This role requires strong analytical skills and the ability to troubleshoot effectively.",
    responsibilities: [
      "Provide support for mobile apps developed in Flutter.",
      "Identify and resolve technical issues.",
      "Assist in testing and deploying new features.",
      "Collaborate with the mobile app development team.",
      "Ensure app performance and usability.",
    ],
    qualifications: [
      "Experience with Flutter and mobile app development.",
      "Proficient in Dart programming language.",
      "Knowledge of mobile app lifecycle and deployment.",
      "Strong communication and problem-solving skills.",
      "Ability to manage time effectively.",
    ],
    officeTime: "9:00 AM - 6:00 PM",
    vacancy: 1,
    jobType: "On-site",
    salary: "25-60",
    workDays: "Sat - Thu (Alt. Saturday Off)",
    location: "Dhaka, Bangladesh",
  },
];
