export const jobData = [
  {
    jobTitle: "Web Developer",
    jobDescription:
      "As a Web Developer, you'll be responsible for designing, coding, and modifying websites, from layout to function, according to client specifications. You will collaborate closely with designers and other developers to create visually appealing sites that feature user-friendly design and clear navigation. Stay updated on emerging technologies.",
    responsibilities: [
      "Develop responsive and dynamic websites.",
      "Collaborate with designers to match visual design intent.",
      "Maintain, expand, and scale websites.",
      "Stay updated on the latest web trends.",
      "Ensure site security and data protection.",
      "Optimize site performance and speed.",
    ],
    qualifications: [
      "Proficiency in HTML, CSS, JavaScript, and frameworks like React or Angular.",
      "Experience with server-side technologies (Node.js, PHP).",
      "Strong problem-solving skills.",
      "Familiarity with responsive design principles.",
      "Ability to work independently and as part of a team.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 3,
    education: "Bachelor's or Master's degree in Computer Science or a related field from a recognized university is preferred.However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 1 + years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "31 September, 2024",
    salary: "TK 25-60K (Based on experience)",
    location: "Chittagong, Bangladesh",
  },
  {
    jobTitle: "Digital Marketing Specialist",
    jobDescription:
      "The Digital Marketing Specialist will focus on managing online marketing strategies, analyzing data to optimize campaigns, and increasing brand awareness. You will be tasked with planning and executing digital marketing campaigns, including web, SEO/SEM, email, social media, and display advertising. You will also analyze and report on campaign performance.",
    responsibilities: [
      "Develop and execute digital marketing strategies.",
      "Manage SEO and SEM strategies.",
      "Analyze and optimize advertising campaigns.",
      "Create content for social media platforms.",
      "Collaborate with the sales team for better results.",
      "Track and report website traffic and social media performance.",
    ],
    qualifications: [
      "Experience with SEO, Google Analytics, and SEM.",
      "Proficient in social media marketing.",
      "Strong analytical and project management skills.",
      "Excellent communication and teamwork skills.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 2,
    education: "Bachelor's or Master's degree in Computer Science or a related field from a recognized university is preferred.However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    salary: "TK 20-45k (Based on experience)",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 2 years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "31 September, 2024",
    location: "Chittagong, Bangladesh",
  },
  {
    jobTitle: "Sales Representative (Live Presenter)",
    jobDescription:
      "We are seeking an energetic and approachable Sales Representative who is confident in front of the camera to engage with customers through live presentations. The ideal candidate should possess excellent communication skills, be able to build relationships with potential clients and demonstrate a passion for driving sales through engaging content and high-quality customer service.",
    responsibilities: [
      "Conduct live sessions to promote and sell products to online audiences.",
      "Interact with viewers, answer questions, and encourage purchases during live streams.",
      "Develop and maintain strong relationships with customers.",
      "Handle customer inquiries through phone, live chat, and social media.",
      "Collaborate with the team to plan and execute engaging and effective live presentations.",
    ],
    qualifications: [
      "Comfortable in front of the camera with a confident and engaging on-screen presence.",
      "Strong communication and interpersonal skills.",
      "Knowledge of online content strategy.",
      "Previous experience in sales or customer service is a plus.",
      "Enthusiasm for customer engagement and product promotion.",
      "Able to work independently and within a team environment.",
      "Age: Not more than 30 years old.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    education: "Minimum of graduation in any discipline. However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    vacancy: 1,
    jobType: "On-site",
    jobCategory: "Full-time",
    experience: " 1 years",
    salary: "Negotiable",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "20 October, 2024",
    location: "Chittagong, Bangladesh",
  },
];
